import rouletteBORD from "../../assets/images/rolettetable.png";

export const style = {
    root: {
      maxWidth: "400px",
      width: "100%",
      backgroundColor: "#000000",
      height: "85vh",
      overflow: "hidden",
      marginTop: "auto",
      position: "relative",
      backgroundImage: `url(${rouletteBORD})`,
      backgroundSize: "100% 100%",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "right",
      // transform: 'rotate(-90deg) !important',
      // left: '22% !important',
    },
  
    red: {
      "&>p": {
        background: "red",
        width: "60%",
        borderRadius: "60%",
        fontSize: "10px",
        fontWeight: 600,
        color: "white",
      },
    },
    black: {
      "&>p": {
        background: "black",
        width: "60%",
        borderRadius: "60%",
        fontSize: "10px",
        fontWeight: 600,
        color: "white",
      },
    },
    bettable: {
      width: "40%",
      height: "63%",
      position: "absolute",
      left: "30%",
      top: "2%",
    },
    btn1: {
      padding: 0,
      border: "1px solid white",
      // width: "20%",
      borderRadius: "0px",
      height: "100%",
      transform: "rotate(-180deg)",
      "&>p": {
        fontSize: "10px",
        fontWeight: 600,
        color: "white",
      },
    },
    btn2: {
      padding: 0,
      border: "1px solid white",
      // width: "33.33333%",
      borderRadius: "0px",
      // height: "25%",
      transform: "rotate(-180deg)",
    },
    btn3: {
      padding: 0,
      border: "1px solid white",
      // width: "100%",
      borderRadius: "0px",
      // fontSize: "10px",
      color: "white",
      fontWeight: 600,
      height: "100%",
      "&>p": {
        transform: "rotate(-270deg)",
        fontSize: "12px",
        fontWeight: 600,
        color: "white",
      },
    },
    btn4: {
      padding: 0,
      fontSize: "12px",
      fontWeight: 900,
      color: "white",
      position: "relative",
      left: "43%",
      background: "green",
      width: "20px",
      height: "20px",
      borderRadius: "50%",
    },
    rotatingElement: { animation: "$rotateInfinite 4s linear infinite" },
    "@keyframes rotateInfinite": {
      "0%": { transform: "rotate(0deg)" },
      "100%": { transform: "rotate(360deg)" },
    },
    naiming: {
      background:
        "linear-gradient(to right,#BF953F, #FCF6BA, #B38728, #FBF5B7, #AA771C)",
      width: "120px",
      transform: "rotate(90deg)",
      position: "absolute",
      top: "7%",
      left: "-7%",
      borderRadius: "5px",
      "&>p:nth-child(1)": {
        color: "black",
        fontSize: "13px",
        fontWeight: "600",
        textAlign: "center",
      },
      "&>p:nth-child(2)": {
        color: "white",
        fontSize: "13px",
        fontWeight: "600",
        padding: "5px 5px",
        background: "#15158f",
        width: "80%",
        margin: "auto",
        marginBottom: "5px",
        borderRadius: "2px",
      },
    },
    naiming2: {
      background:
        "linear-gradient(to right,#BF953F, #FCF6BA, #B38728, #FBF5B7, #AA771C)",
      width: "120px",
      transform: "rotate(90deg)",
      position: "absolute",
      top: "28%",
      left: "-7%",
      borderRadius: "5px",
      "&>p:nth-child(1)": {
        color: "black",
        fontSize: "13px",
        fontWeight: "600",
        textAlign: "center",
      },
      "&>p:nth-child(2)": {
        color: "white",
        fontSize: "13px",
        fontWeight: "600",
        padding: "5px 5px",
        background: "#15158f",
        width: "80%",
        margin: "auto",
        marginBottom: "5px",
        borderRadius: "2px",
      },
    },
    naiming3: {
      background:
        "linear-gradient(to right,#BF953F, #FCF6BA, #B38728, #FBF5B7, #AA771C)",
      width: "120px",
      transform: "rotate(90deg)",
      position: "absolute",
      top: "60%",
      left: "-11%",
      borderRadius: "5px",
      padding: "15px",
      "&>p:nth-child(1)": {
        color: "black",
        fontSize: "13px",
        fontWeight: "600",
        textAlign: "center",
      },
      "&>p:nth-child(2)": {
        color: "white",
        fontSize: "13px",
        fontWeight: "600",
        padding: "5px 5px",
        background: "#15158f",
        width: "80%",
        margin: "auto",
        marginBottom: "5px",
        borderRadius: "2px",
      },
    },
    naiming4: {
      background: "red",
      width: "120px",
      transform: "rotate(90deg)",
      position: "absolute",
      bottom: "8%",
      left: "-9%",
      borderRadius: "5px",
      "&>p:nth-child(1)": {
        color: "black",
        fontSize: "13px",
        fontWeight: "600",
        textAlign: "center",
      },
      "&>p:nth-child(2)": {
        color: "white",
        fontSize: "13px",
        fontWeight: "600",
        padding: "5px 5px",
        background: "red",
        width: "80%",
        margin: "auto",
        marginBottom: "5px",
        borderRadius: "2px",
      },
    },
    naiming5: {
      background: "red",
      width: "120px",
      transform: "rotate(90deg)",
      position: "absolute",
      bottom: "34%",
      left: "5%",
      borderRadius: "5px",
      "&>p:nth-child(1)": {
        color: "black",
        fontSize: "13px",
        fontWeight: "600",
        textAlign: "center",
      },
      "&>p:nth-child(2)": {
        color: "white",
        fontSize: "13px",
        fontWeight: "600",
        padding: "5px 5px",
        background: "red",
        width: "80%",
        margin: "auto",
        marginBottom: "5px",
        borderRadius: "2px",
      },
    },
    naiming6: {
      background:
        "linear-gradient(to right,#BF953F, #FCF6BA, #B38728, #FBF5B7, #AA771C)",
      width: "120px",
      transform: "rotate(90deg)",
      position: "absolute",
      top: "7%",
      left: "7%",
      borderRadius: "5px",
      textAlign: "center",
      "&>p:nth-child(1)": {
        color: "black",
        fontSize: "13px",
        fontWeight: "600",
        textAlign: "center",
      },
      "&>p:nth-child(2)": {
        color: "white",
        fontSize: "13px",
        fontWeight: "600",
        padding: "5px 5px",
        background: "#15158f",
        width: "80%",
        margin: "auto",
        marginBottom: "5px",
        borderRadius: "2px",
      },
    },
    countdownOuter: {
      position: "absolute",
      width: "75px",
      height: "75px",
      background: "black",
      bottom: "4.5%",
      left: "15%",
      border: "2px solid white",
      borderRadius: "10px",
      outline: "10px solid black",
      boxSizing: "border-box",
    },
    winnerlooserouter: {
      padding: "2px",
      border: "2px solid #C9A553",
      position: "absolute",
      right: "-2%",
      transform: "rotate(90deg)",
      top: "28%",
      width: "120px",
      borderRadius: "5px",
    },
    winnerlooserouter2: {
      padding: "2px",
      border: "2px solid #C9A553",
      position: "absolute",
      right: "0%",
      transform: "rotate(90deg)",
      top: "8%",
      width: "100px",
      borderRadius: "5px",
    },
    winnerlooserouter3: {
      padding: "2px",
      border: "2px solid #C9A553",
      position: "absolute",
      right: "2%",
      transform: "rotate(90deg)",
      top: "48%",
      width: "70px",
      height: "50px",
      borderRadius: "5px",
      background: "black",
    },
    winnerLooserList: {
      display: "flex",
      justifyContent: "space-around",
      width: "100%",
      "&>p:nth-child(1)": {
        fontSize: "12px",
        fontWeight: "900",
        color: "yellow",
      },
      "&>p:nth-child(2)": {
        fontSize: "12px",
        fontWeight: "900",
        color: "#90ff90",
      },
      "&>p:nth-child(3)": { fontSize: "12px", fontWeight: "900", color: "red" },
    },
    winnerLooserList2: {
      width: "100%",
      "&>p": {
        fontSize: "12px",
        fontWeight: "600",
        color: "yellow",
        textAlign: "center",
      },
    },
    winnerLooserList3: {
      width: "100%",
      "&>p": {
        fontSize: "35px",
        fontWeight: "600",
        color: "yellow",
        textAlign: "center",
      },
    },
  };